### ISSUE TITLE
Support selecting Quarkus platform version in project wizard

### ISSUE THREAD

**Issue by rgrunber** [xorye/vscode-quarkus#393]
There is now an option to select the Quarkus platform version on https://code.quarkus.io/ . The query string parameter controlling this appears to be `S`. See https://github.com/redhat-developer/vscode-quarkus/blob/master/src/wizards/generateProject/generationWizard.ts & https://github.com/redhat-developer/vscode-quarkus/blob/master/src/utils/requestUtils.ts#L69

**Comment by AlexXuChen** [comment]
@rgrunber What step should the quarkus platform version selection be in the wizard? I was thinking before groupId, since that's how it shows up on https://code.quarkus.io/

**Comment by rgrunber** [comment]
Yup, I think it should be the first option because it seems to change the state of the available project extensions (dependencies) you can choose. So you might get different options for 2.2 than 2.1.

Maybe the platform version isn't passed directly to the downloading of the project, but rather the code that queries the list of available extensions. I haven't checked but that might be the case.

**Comment by fbricon** [comment]
+1 to selecting the quarkus version 1st

**Comment by rgrunber** [comment]
@AlexXuChen , I would use the web developer tooling for your favourite browser on https://code.quarkus.io/. Specifically the functionality that records the network traffic. It'll be a huge help in understanding how the platform versions are determined, and how the extensions are discovered based on that.

**Comment by rgrunber** [comment]
For future reference : https://code.quarkus.io/q/swagger-ui/
