### ISSUE TITLE
When generating a project without starter code, the Resource name step should be skipped

### ISSUE THREAD

**Issue by fbricon** [xorye/vscode-quarkus#396]
Right now, when generating a quarkus project, you set the Resources name and at the end, decide you don't want to include starter code. This is backward. You should select if starter code is included and then, if it's still relevant, ask to about the resource name.

**Comment by AlexXuChen** [comment]
Atm, we have the step number at the top of the wizard (e.g. Quarkus Tools (x/9)). If we choose "Do not include starter code", then we no longer have 9 total steps, but rather 8. What should be done about the displayed total?

I was thinking that the "Sample Code" step number remains the same as the "Starter Code" step number (i.e. we always have x/8 in this case)
