### ISSUE TITLE
support profile aware properties

### ISSUE THREAD

**Issue by maxandersen** [xorye/vscode-quarkus#400]
see https://quarkus.io/guides/config-reference#profile-aware-files

you can have `application-<profile>.properties` now.

atm content assist and validation seems to ignore them.

**Comment by angelozerr** [comment]
If you install last vsix (not released) of vscode-quarkus, it should work, but it's not perfect on Java file side. I created the PR https://github.com/eclipse/lsp4mp/pull/180 to manage correctly profile inside Java file (for hover and diagnostics) for microprofile-config-profile.properties and  microprofile-profile.properties

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lsp4mp/pull/180
