### ISSUE TITLE
Unable to access a critical quarkus repository.

### ISSUE THREAD

**Issue by MintakaB** [xorye/vscode-quarkus#401]
Issue Type: <b>Bug</b>

Unable to reach http://code.quarkus.io/api/extensions

The url is accesible with any browser however not from the extension. 

Extension version: 1.9.0
VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T11:59:27.195Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (15.75GB free)|
|Process Argv|--crash-reporter-id 1c54aadb-c049-4a59-a74f-91f5b7bdd35e|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by j4fm** [comment]
Same here. I'm not behind any proxy and was working normally until yesterday, no network changes.  Other extensions in VS Code can reach out, and I can also access the above URL in the web browser just fine.

Using the **./mvnw quarkus:add-extension -Dextensions="<extension name>"** command as a workaround works fine.

**Comment by angelozerr** [comment]
It seems that it's a SSL problem.

@rgrunber @AlexXuChen we have the same problem in master, because when I disable SSL check by updating the line https://github.com/redhat-developer/vscode-quarkus/blob/734f46a3230309820ca3b9f538fbf390ede9561a/src/utils/codeQuarkusApiUtils.ts#L119

with:
 
```ts
https.get(url, {
      rejectUnauthorized: false
    } as https.RequestOptions, (res: IncomingMessage) => {
```

it works, but it's not a clean solution to disable SSL.

**Comment by fbricon** [comment]
@ia3andy @maxandersen is this a known issue?

**Comment by ia3andy** [comment]
@fbricon I never heard about this, maybe there is a problem with the certificate?

**Comment by fbricon** [comment]
@angelozerr can you try with an older version of vscode?

**Comment by rgrunber** [comment]
The full error :

```
Error: certificate has expired\n\tat TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)\n\tat TLSSocket.emit (events.js:315:20)\n\tat TLSSocket._finishInit (_tls_wrap.js:932:8)\n\tat TLSWrap.onhandshakedone (_tls_wrap.js:706:12)\n\tat TLSWrap.callbackTrampoline (internal/async_hooks.js:131:14) {code: 'CERT_HAS_EXPIRED', stack: 'Error: certificate has expired\n\tat TLSSocket.…ckTrampoline (internal/async_hooks.js:131:14)', message: 'certificate has expired'}
```

**Comment by ia3andy** [comment]
@rgrunber it's weird when I look at the certificate it says it's valid until november.

**Comment by rgrunber** [comment]
~~Note the expires near the bottom mentions October 4th~~ ?


```
$ curl -vvI "https://code.quarkus.io"
*   Trying 54.235.201.2:443...
..
..
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=code.quarkus.io
*  start date: Aug 19 14:40:34 2021 GMT
*  expire date: Nov 17 14:40:32 2021 GMT
...
...
< expires: Mon, 04 Oct 2021 14:01:59 GMT
expires: Mon, 04 Oct 2021 14:01:59 GMT
< cache-control: max-age=0
cache-control: max-age=0
< cache-control: no-cache
cache-control: no-cache
...
...
```

^ It's just caching as mentioned below, not of interest.

**Comment by ia3andy** [comment]
thanks a lot @rgrunber I am on it

**Comment by ia3andy** [comment]
@rgrunber `expires: Mon, 04 Oct 2021 14:01:59 GMT` is for cache,
certificate is `*  expire date: Nov 17 14:40:32 2021 GMT`

**Comment by jeffmaury** [comment]
Seems related to nodejs, @evidolob mentioned a similar issue on Friday, the certificate seems ok

**Comment by sebastienblanc** [comment]
As a side effect It's also not possible to go through the whole "Quarkus: Generate a Quarkus project" process ...

**Comment by maxandersen** [comment]
issue says http://code.quarkus.io/api/extensions - I assume its meant to be http://code.quarkus.io/api/extensions ?  and its not some funky redirect from http to https certificate mixup that is happening ?

**Comment by rgrunber** [comment]
On the latest commit, the final value sent to `https.get`, is `https://code.quarkus.io/q/openapi` & `https://code.quarkus.io/openapi` (to determine the correct endpoint), followed by `https://code.quarkus.io/api/streams`. They all fail with the same error mentioned in https://github.com/redhat-developer/vscode-quarkus/issues/401#issuecomment-933509742 . We do have code to handle the redirect, but it's not triggered.

**Comment by maxandersen** [comment]
Any idea what is the cause ? Updated dependency that has buggy redirect implementation or how ?

**Comment by evidolob** [comment]
It might be related to https://github.com/microsoft/vscode/issues/134244

**Comment by ia3andy** [comment]
Maybe you should edit the bug description?

**Comment by angelozerr** [comment]
> It might be related to microsoft/vscode#134244

Thanks @evidolob for your feedback.

I tried vscode-quarkus which has been released and vscode-quarkus from master  with **VSCode Insider** and the both are working!

**Comment by sebastienblanc** [comment]
Yes did the test with Insider and it works perfectly. So I guess we need to wait for the new VS Code release ?

**Comment by angelozerr** [comment]
> Yes did the test with Insider and it works perfectly. So I guess we need to wait for the new VS Code release ?

Thanks for your feedback, yes we need to wait for new VSCode release.

**Comment by jeffmaury** [comment]
> 
> 
> Yes did the test with Insider and it works perfectly. So I guess we need to wait for the new VS Code release ?

No need, take a true IDE like IntelliJ or Eclipse 😄

**Comment by angelozerr** [comment]
I was not aware that there was Quarkus support for IJ and Eclipse IDE, nice :)

**Comment by fbricon** [comment]
vscode 1.61.0 is out, fixing this issue.

**Comment by robertkylethomas** [comment]
1.62.3 its still not working 

Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by rgrunber** [comment]
> 1.62.3 its still not working
> 
> Version: 1.62.3 (user setup) Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247 Date: 2021-11-17T08:11:14.551Z Electron: 13.5.2 Chrome: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.17134

It's happening again, https://github.com/microsoft/vscode/issues/136787 .

Setting `"http.systemCertificates": false` should work around the issue (assuming this isn't some other issue occuring).
