### ISSUE TITLE
Quarkus API URL should use https

### ISSUE THREAD

**Issue by fbricon** [xorye/vscode-quarkus#402]
https://github.com/redhat-developer/vscode-quarkus/blob/734f46a3230309820ca3b9f538fbf390ede9561a/package.json#L173

**Comment by angelozerr** [comment]
@fbricon it seems code replace http with https https://github.com/redhat-developer/vscode-quarkus/blob/734f46a3230309820ca3b9f538fbf390ede9561a/src/utils/codeQuarkusApiUtils.ts#L95

**Comment by fbricon** [comment]
that's a hack! Shouldn't happen in the first place. You wouldn't be able to run against the quarkus api server running locally on a non https server.

**Comment by fbricon** [comment]
and it's only for getting the list of streams. Other places still use the package.json value

**Comment by rgrunber** [comment]
Yup, I've noticed this. We have an http value in package.json which can be overriden by another default when it's parsed, and then we adjust that again with a regex/replace match. Seems we can remove those replacements by just using https everywhere.

**Comment by fbricon** [comment]
Don't assume https. https on production is a given, but running against a locally running api server means probably http.

**Comment by rgrunber** [comment]
> Don't assume https. https on production is a given, but running against a locally running api server means probably http.

Whoops, I meant just our default values for https://github.com/redhat-developer/vscode-quarkus/blob/master/package.json#L173 & https://github.com/redhat-developer/vscode-quarkus/blob/master/src/definitions/constants.ts#L39 should be https if not already and we should avoid doing replacements on a user-defined value.
