### ISSUE TITLE
(Notice) Dropping shortId support on code.quarkus.io/api

### ISSUE THREAD

**Issue by ia3andy** [xorye/vscode-quarkus#421]
FYI: https://github.com/quarkusio/code.quarkus.io/pull/680

I searched for `shortId` in the repo and didn't find any reference to it.

You can close this issue if it is not used anymore.

**Comment by fbricon** [comment]
I think we're good: 
https://github.com/redhat-developer/vscode-quarkus/blob/caed8f55d07015f517331b65ac4137bbfbf91d18/src/utils/requestUtils.ts#L76-L84
