### ISSUE TITLE
Direct index access highlighting looks bad

### ISSUE THREAD

**Issue by fbricon** [xorye/vscode-quarkus#432]
Accessing a list or array by index directly doesn't render properly:
<img width="158" alt="Screenshot 2022-01-11 at 19 37 16" src="https://user-images.githubusercontent.com/148698/149002060-1fad3d7b-9d94-405a-b116-b2288a9d5ffa.png">

**Comment by AlexXuChen** [comment]
While I'm able to make the highlighting consistent:
![Screenshot from 2022-01-11 14-19-20](https://user-images.githubusercontent.com/26389510/149008788-c63217fc-fa1f-40d6-b2f8-84fe0a594976.png)
The error still persists, which is handled in:
https://github.com/redhat-developer/quarkus-ls/blob/da79fdb2413dd5e73764d426f682201dd9982156/qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/QuteErrorCode.java#L36
I believe the solution is to check if the referenced object is iterable, and ignore the error with https://github.com/redhat-developer/quarkus-ls/issues/451

**Comment by fbricon** [comment]
You need https://github.com/redhat-developer/quarkus-ls/pull/528 for proper array support
