### ISSUE TITLE
Promote experimental Qute validation

### ISSUE THREAD

**Issue by angelozerr** [xorye/vscode-quarkus#438]
The Qute validation manages syntax error and semantic error (like undefined varriable, unknown property, etc). But it has some limitation like:

 * don't support infox notation
 * don't support bracket notation for property (ex : item['name']) 

It means that there are error although it should not have errors. See comments at https://github.com/redhat-developer/quarkus-ls/issues/451#issuecomment-1008876522

@maxandersen suggested `disable the Qute validation by default`.

To promote that Qute support is able to validate Qute template, it should be nice to show the first time a popup which ask if user want to activate the Experimental Qute validation:

 * yes -> will update the `quarkus.tools.qute.validation.enabled ` settings to true
 * no -> do nothing

@fbricon @rgrunber as the popup must be displayed just the first time after (and not open this popup each time we open vscode), I think we need to manage a flag like `openPopupToActivateExperimentalQuteValidation`, where can we store it? I think vscode-quarkus already manage this kind of flag if I remember to open Overview page of Quarkus (not sure for that).

**Comment by fbricon** [comment]
you can use globalState to store the information. See https://stackoverflow.com/a/51822055/753170
