### ISSUE TITLE
Toggle button on Qute editor to enable/disable validation

### ISSUE THREAD

**Issue by angelozerr** [xorye/vscode-quarkus#448]
It should be nice to provide a toggle button on the the top right of the editor to enable/disable validation. 

We need to know the validation state (eabled or disabled?) of the opened template, and it will require to implement a custom command on Qute LS side. The state of the button will be synchronized with the vaidation state.

Click on button will active/desactive the validation for the Qute template. In other words it will update:

 * qute.validation.enabled to true in the workspace folder scope
 * remove the template from qute.validation.excluded pattern.

**Comment by angelozerr** [comment]
Instead of updating directly the settings with `workspace.getConfiguration().update` when button will be clicked, it should be better to consume `QuteClientCommandConstants.COMMAND_CONFIGURATION_UPDATE` like code action from Qute LS does. See https://github.com/redhat-developer/vscode-quarkus/blob/dc16889d3a8684138cbfa8005a7ba52460b5a630/src/qute/commands/registerCommands.ts#L77

**Comment by angelozerr** [comment]
For getting the validation state of a given template, we must implement an `IDelegateCommandHandler` like https://github.com/redhat-developer/quarkus-ls/blob/76ab820fd35fa30a9996d460a8f15dd4392b1bc3/qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/commands/QuteGenerateCommandHandler.java#L31 on Qute LS side.

This command could returns a boolean or perhaps the settings which says why a qute template validation is disabled? 

I'm working on that...

**Comment by rgrunber** [comment]
https://code.visualstudio.com/api/references/when-clause-contexts#check-a-setting-in-a-when-clause may be useful if you need to use 2 commands that have enablement criteria (eg. `when` caluse) that are negations of each other. You can also set a custom context. This depends on the clause being re-evaluated on every interaction with the commands though.
