### ISSUE TITLE
Requires maven to be installed globally, doesn't detect maven installed using sdkman

### ISSUE THREAD

**Issue by agilob** [xorye/vscode-quarkus#452]
I have packages like java, mvn, gradle installed locally using sdkman in `/home/agilob/.sdkman/candidates/maven/current/bin/mvn`, which do not seem to be detected by the plugin. Running "quarkus debug" action results in:

```
> Executing task: mvn quarkus:dev  <

zsh:1: command not found: mvn
The terminal process "zsh '-c', 'mvn quarkus:dev '" failed to launch (exit code: 127).
```

when I run the same command locally:

```
❯ which mvn
/home/agilob/.sdkman/candidates/maven/current/bin/mvn
❯ zsh -c 'mvn quarkus:dev '
[INFO] Scanning for projects...
```

mvn is detected.

The plugin also doesn't read settings from maven plugin, which I also have configured:
```
"maven.executable.options": "/home/agilob/.sdkman/candidates/maven/current/bin/mvn",
```

this can be fixed by installing maven globally for whole OS.

**Comment by fbricon** [comment]
Is`.sdkman/candidates/maven/current/bin/mvn` added to the $PATH, when running from a terminal?
Can you try opening VS Code from the terminal (provided you [installed the 'code' command](https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line)) , 
>cd yourfolder
code .

Try running the Quarkus: Debug command

**Comment by agilob** [comment]
Is.sdkman/candidates/maven/current/bin/mvn added to the $PATH, when running from a terminal?

Yes, sdkman automatically adds enabled packages to $PATH

Starting code from cli in the directory works fine and "quarkus debug" is working as well.

**Comment by fbricon** [comment]
so for some reason vscode doesn't load your shell environment on startup (maybe it's too slow), which prevents it from sharing the proper $PATH variable to its extensions (including vscode-quarkus). Seems to be either a config issue on your side or an upstream vscode problem.
