### ISSUE TITLE
Linked editing doesn't work if variable is used as a parameter into a section

### ISSUE THREAD

**Issue by fbricon** [xorye/vscode-quarkus#500]
See item in the #linkItem user tag: 
```html
{#for item in items}
      <li>
            {#linkItem name=item.name /} 
            {#if item.price < 15}
              {item.price}
            {#else}
              <del>{item.price}</del> <strong>{item.discountedPrice}</strong>
            {/if}
      </li>
{/for}
```
<img width="950" alt="Screenshot 2022-05-16 at 19 02 52" src="https://user-images.githubusercontent.com/148698/168645947-0c350f56-890d-465b-8c07-9be6b2733e7c.png">

**Comment by angelozerr** [comment]
I fixed the bug for the linked editing range, see https://github.com/redhat-developer/quarkus-ls/pull/638

But there are the same problem king with highlight and with definition that I fixed too.
