### ISSUE TITLE
Display error when Quarkus application is built for Qute

### ISSUE THREAD

**Issue by angelozerr** [xorye/vscode-quarkus#508]
Once https://github.com/quarkusio/quarkus/pull/25810 will be merged, we could display errors in Qute template file by using `problemMatcher` from the task.

See https://github.com/quarkusio/quarkus/issues/25724 for detail of this issue.

**Comment by rgrunber** [comment]
Relevant https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher . Might be good to read the full thing to understand what needs to be done programmatically.

**Comment by angelozerr** [comment]
Exactly, I speak about that  too in my comment https://github.com/quarkusio/quarkus/issues/25724
