### ISSUE TITLE
Quarkus extension seems to be broken in VS Code

### ISSUE THREAD

**Issue by danieloh30** [xorye/vscode-quarkus#528]
I don't think the Quarkus extension doesn't work in the latest VS Code. For example, when I'm typing certain keys (e.g. quarkus.kubernetes.), it should show all relevant values automatically. But after I updated the latest VS Code, it doesn't anymore.

Here are my VS Code and Quarkus extension versions:
![image](https://user-images.githubusercontent.com/14066977/180454493-1258ee7c-9481-4bad-a94b-3f877bdffbf3.png)

![image](https://user-images.githubusercontent.com/14066977/180454586-dfe165ae-dffb-4c15-8e74-eb4dcee5c0de.png)

**Comment by rgrunber** [comment]
See https://github.com/redhat-developer/vscode-quarkus/issues/526 . Marking this as a duplicate. We just need to release 1.11.0. Downgrading to vscode-java 1.8.0 should also fix this.

**Comment by danieloh30** [comment]
@rgrunber when will 1.11.0 be released? How to downgrade vscode-java 1.8.0?

**Comment by danieloh30** [comment]
nvm. I just found that you mentioned the release date (July 25th) on slack channel.

**Comment by rgrunber** [comment]
![install-another-version](https://user-images.githubusercontent.com/1417342/180500041-f97f70dd-c133-4f04-9b11-a51fd41f2146.gif)

Yeah, ASAP is ideal for this. Another possibility is to just use the development versions of vscode-quarkus + vscode-microprofile :
https://download.jboss.org/jbosstools/vscode/snapshots/vscode-microprofile/vscode-microprofile-0.5.0-238.vsix https://download.jboss.org/jbosstools/vscode/snapshots/vscode-quarkus/vscode-quarkus-1.11.0-544.vsix

**Comment by danieloh30** [comment]
Awesome. thx @rgrunber

**Comment by danieloh30** [comment]
I downgraded 1.8.0 and installed the above 2 extensions manually but the issue is still the same
<img width="759" alt="image" src="https://user-images.githubusercontent.com/14066977/180519845-c56fd1eb-7a1f-440f-8dce-2586b965f7f1.png">

**Comment by rgrunber** [comment]
- The above 2 (snapshot) versions, vscode-microprofile-0.5.0* & vscode-quarkus-1.11.0* would need vscode-java 1.9.0
- The previous 2 versions, vscode-microprofile-0.4.0 & vscode-quarkus-1.10.0 would need vscode-java 1.8.0

Normally the quarkus vscode extensions isn't so tightly dependent on a particular version of vscode-java, but there was a change we reacted to in vscode-java 1.8.0 -> 1.9.0 (coming from m2e)  that made the old versions unable to run in the runtime of the newer vscode-java, and the newer ones unable to run in the runtime of the older vscode-java.

**Comment by danieloh30** [comment]
OK. Let me try to downgrade 2 versions too.

**Comment by danieloh30** [comment]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/14066977/180563838-179eddd8-4a53-4126-962c-8b580c6608ad.png">
<img width="739" alt="image" src="https://user-images.githubusercontent.com/14066977/180564030-1b10c9e6-9b89-44b4-afb0-78738ae42142.png">
<img width="739" alt="image" src="https://user-images.githubusercontent.com/14066977/180564130-3f5a2bdb-34d1-4608-8d5a-9dede8c13286.png">
Still doesn't work. Maybe I need to upgrade all extensions back to the latest and wait for `1.11.0` :(

**Comment by rgrunber** [comment]
Can you also confirm vscode-microprofile (which should be installed as a dependency of vscode-quarkus) was at version 0.4.0 when you tried the downgrade approach ?

**Comment by danieloh30** [comment]
Yeah I did
<img width="684" alt="image" src="https://user-images.githubusercontent.com/14066977/180798129-b5650dd8-0648-4a9d-83d6-508a4b979692.png">

**Comment by rgrunber** [comment]
You're absolutely right. It's still broken, just in a different way.

In https://github.com/redhat-developer/vscode-quarkus/issues/526, the issue was the quick-pick for adding new extensions wasn't coming up. That breakage was from m2e removal of org.eclipse.m2e.lifecycle.defaults bundle, so downgrading to 1.8.0 fixed that.

However there is still another breakage on 1.8.0. m2e bumped some of the artifact API that also is incompatible. Apparently this doesn't break the quick-pick menu but it is seen when one attempts to trigger completion in an application properties file.

```
!ENTRY org.eclipse.core.jobs 4 2 2022-07-25 10:24:01.118
!MESSAGE An internal error occurred during: "MicroProfile properties collector".
!STACK 0
java.lang.NoSuchMethodError: 'java.lang.String org.eclipse.m2e.core.embedder.ArtifactKey.getGroupId()'
	at org.eclipse.lsp4mp.jdt.internal.core.utils.DependencyUtil.getLocalArtifactFile(DependencyUtil.java:91)
	at org.eclipse.lsp4mp.jdt.internal.core.utils.DependencyUtil.getArtifact(DependencyUtil.java:63)
	at org.eclipse.lsp4mp.jdt.internal.core.MavenArtifactResolver.getArtifact(MavenArtifactResolver.java:44)
	at com.redhat.microprofile.jdt.internal.quarkus.core.properties.QuarkusConfigRootProvider.addArtifactInClasspath(QuarkusConfigRootProvider.java:178)
	at com.redhat.microprofile.jdt.internal.quarkus.core.properties.QuarkusConfigRootProvider.contributeToClasspath(QuarkusConfigRootProvider.java:160)
	at com.redhat.microprofile.jdt.internal.quarkus.core.properties.QuarkusConfigRootProvider.contributeToClasspath(QuarkusConfigRootProvider.java:102)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.contributeToClasspath(PropertiesManager.java:346)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getJavaProject(PropertiesManager.java:324)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.configureSearchClasspath(PropertiesManager.java:179)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:135)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:110)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:101)
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandler.lambda$0(MicroProfileDelegateCommandHandler.java:105)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

What about trying to downgrade to 1.7.0 of vscode-java ?

**Comment by danieloh30** [comment]
how about the other dependencies? Shouldn't 1.11.0 be released today?

**Comment by danieloh30** [comment]
Ok. 1.7.0 works for me

**Comment by rgrunber** [comment]
Yes, I'm in the process of releasing 1.11.0.

**Comment by danieloh30** [comment]
Cool. Please update me once you're done! I'm happy to be a beta tester :)

**Comment by rgrunber** [comment]
vscode-microprofile 0.5.0 & vscode-quarkus 1.11.0 have just been published on the marketplaces. I was able to confirm with some others that it'll fix the issues we've been having.

Note that vscode-java will need to be at 1.9.0 (latest release) or newer (pre-release).

**Comment by danieloh30** [comment]
Ok. Let me try it now.

**Comment by danieloh30** [comment]
Yay! It works for me too. Thx:)

**Comment by danieloh30** [comment]
@rgrunber I just have the same issue when I created a new Quarkus 2.11.1 project. Is this related to a new Quarkus version? I don't think so but this issue happens agagin.
