### ISSUE TITLE
No option to hid "deploy to openshift" button

### ISSUE THREAD

**Issue by alejandro-du** [xorye/vscode-quarkus#535]
There's no option to hide the rather intrusive "Deploy to OpenShift" button. It's displayed every time I open a Java file even if the project doesn't use Quarkus. Moreover, clicking it just shows the error "No Quarkus projects were detected in this folder", so what's the point of always displaying this? At the very least, there should be an option to permanently hide the button.

**Comment by rgrunber** [comment]
Agreed. I think this would be improved by https://github.com/redhat-developer/vscode-quarkus/issues/497 . I think the Quarkus extension can activate, but not make any contributions to the UI / start its language server unless the workspace really contains a Quarkus project.

**Comment by rgrunber** [comment]
This should be resolved now. A lot of the menu contributions rely on the `quarkusProjectExistsOrLightWeight` context being set but we're now more restrictive of the activation (which sets this context).

This will be part of the eventual 1.12.0 release, but for now we also deploy pre-releases to the VS Code Marketplace. Feel free to re-open if there's still a problem we've missed.
