### ISSUE TITLE
Snippets aren't showing

### ISSUE THREAD

**Issue by eniuane** [xorye/vscode-quarkus#551]
### Description

When trying to use snippets the only one showing is the qtrc.

### Context

OS: MacOS 12.6
VSCode: 1.72.2
Quarkus extension: v1.11.0

java --version:
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode)

### Screenshots

<img width="538" alt="image" src="https://user-images.githubusercontent.com/18352755/195957817-0896737a-1372-49b5-a5f4-5aba5bb5640b.png">

**Comment by datho7561** [comment]
Thanks for filling this issue!

We try to filter out the snippets that aren't applicable to the current Quarkus application based on which Quarkus extensions are installed. So, for instance, the `qds` snippet doesn't appear unless you have the Hibernate Quarkus extension installed (eg. the project has `io.quarkus:quarkus-hibernate-orm` as a dependency). Maybe this is what you are running into?

If it is, do you think this behaviour makes sense?

If not, please let us know. Snippets appear to be working for me, but maybe we need to do a more thorough investigation.

**Comment by eniuane** [comment]
Yes I think that makes sense. My point was more on the following ones that I think they should always appear:
- qrc
- qrm
- qtrc
- qntrc

**Comment by datho7561** [comment]
It looks like these snippets have been renamed:
- `qrc` --> `jaxrc`
- `qrm` --> `jaxrm`

This is because they have been moved to vscode-microprofile, since they will work in any MicroProfile project. We should update the documentation to reflect these changes.

I don't know why `qnrtc` isn't appearing yet, I'll have to research more.

**Comment by eniuane** [comment]
I can confirm that with jaxrc and jaxrm they appear! Thanks for the help.

yea, the documentation is a bit misleading now.

**Comment by eniuane** [comment]
@datho7561 Can I open a Pull request to change the README.md?

**Comment by datho7561** [comment]
Ah here is the final missing piece of the puzzle: https://quarkus.io/guides/building-native-image#testing-the-native-executable. We were trying to detect the presence of a class that has been removed.

So we have two tasks: 
1. Update the documentation
2. Fix or remove the context dependency of the `qntrc` snippet

**Comment by datho7561** [comment]
I could also take a look into updating the docs. Sorry, I got distracted by another task for a while.

**Comment by eniuane** [comment]
That's OK, I was trying to help on the project 😄 , but I don't know where to start.

**Comment by datho7561** [comment]
Thank you! Feel free to open a PR, I'm happy to review it!
