### ISSUE TITLE
Migrate from `find-java-home` to `jdk-utils`

### ISSUE THREAD

**Issue by datho7561** [xorye/vscode-quarkus#569]
This would mean that we use the same strategy as in vscode-java.

**Comment by datho7561** [comment]
@JessicaJHee  were you interested in looking into this? If not, I can take a look into it for next sprint

**Comment by JessicaJHee** [comment]
> @JessicaJHee were you interested in looking into this? If not, I can take a look into it for next sprint

Yes I'm interested in this issue! I can take it
