### ISSUE TITLE
when no ./mvnw exist cannot debug quarkus

### ISSUE THREAD

**Issue by maxandersen** [xorye/vscode-quarkus#572]
if no mvnw exist in project debug quarkus fails trying to run `./mvnw quarkus:dev`

...could run `mvn quarkus:dev` to rely on path ...or at least tell user how they configure which command it will run.

**Comment by datho7561** [comment]
If you delete `.vscode/tasks.json` then rerun the "Quarkus: Debug current Quarkus project" command, it should work. However, it would be nice to automatically fix the `tasks.json` when `mvnw` is missing, since it makes sense that some people would delete the `mvnw`.

**Comment by maxandersen** [comment]
But Tasks.json didn't mention ./mvnw ?
