### ISSUE TITLE
Major bug with definition of user tag

### ISSUE THREAD

**Issue by angelozerr** [xorye/vscode-quarkus#579]
I don't know if it is because of the new vscode language client, but there is a major bug with definition for user tag. To reproduce the problem, do Ctrl+Click on an user tag in qute template without click on it (to avoid opening the file)

![image](https://user-images.githubusercontent.com/1932211/216423783-68a12ea8-f580-47a1-bf7a-2f1d5e05038d.png)

And you will see in the trace an infinite of didOpen, didClose of the user tag file name, which report  a lot of diagnostics (because diagnostics is done on didOpen).

To stop those didOpen/didClose, you need to open the user tag file name.

**Comment by datho7561** [comment]
I don't think it's the language client, I tried it on 7.y.z of the language client and was able to reproduce the issue.
