### ISSUE TITLE
Surround with section / comments

### ISSUE THREAD

**Issue by angelozerr** [xorye/vscode-quarkus#581]
Liek we have for vscode-xml surround with tags https://github.com/redhat-developer/vscode-xml/blob/main/docs/Refactor.md#surround-with-tags-wrap

It should really nice to have a surround with section.

Given this Qute template:

`{class}`

It should be nice to to select this expression execute the command surround with section which will generate that:

`{#if condition}{class}{\if}`

@FroMage, @mkouba in XML the surround with tags is very nice, I think we can have similar feature for Qute and having a surroud with comments too.

**Comment by mkouba** [comment]
> Given this Qute template:
> 
> `{class}`
> 
> It should be nice to to select this expression execute the command surround with section which will generate that:
> 
> `{#if condition}{class}{\if}`
> 
> @FroMage, @mkouba in XML the surround with tags is very nice, I think we can have similar feature for Qute and having a surroud with comments too.

Yep, why not. For comments we should do `{! {class} !}`...

**Comment by FroMage** [comment]
+1

**Comment by angelozerr** [comment]
Thanks @mkouba @FroMage for your feedback and glad the feature pleases you.

@JessicaJHee will work on this issue.

**Comment by angelozerr** [comment]
@jeffmaury @sbouchet it should be really nice if IJ and Eclipse will provide too this feature.

 Once the command will be implemented on server side you will need to implement à custom client component which will consume the surround language server command.
