### ISSUE TITLE
request failed on every java file load

### ISSUE THREAD

**Issue by maxandersen** [xorye/vscode-quarkus#586]
I get a notification saying requests failed.

log has this in Qute support view:

```
[Error - 8:17:32 PM] Request textDocument/inlayHint failed.
[object Object]
[Error - 8:17:33 PM] Request textDocument/inlayHint failed.
[object Object]
[Error - 8:17:34 PM] Request textDocument/inlayHint failed.
[object Object]
[Error - 8:17:34 PM] Request textDocument/inlayHint failed.
[object Object]
[Error - 8:17:34 PM] Request textDocument/inlayHint failed.
[object Object]
```

**Comment by angelozerr** [comment]
I think this issue should be fixed in master which uses the last version of vscode language client. 

Could you please install prerelease of vscode microprofile and quarkus please.

**Comment by datho7561** [comment]
I think this is related to the API change I did in vscode-java. @angelozerr I think we need to make sure the java language server is in standard mode before sending delegate commands to it. (I'll look into making this change today).
