### ISSUE TITLE
Show quarkus extensions from other origins

### ISSUE THREAD

**Issue by fbricon** [xorye/vscode-quarkus#599]
The quarkus-quinoa extension is not listed in the new Quarkus project wizard, as it's not part of the core quarkus plugins, but is part of the wider quarkus ecosystem.
However it's visible in https://code.quarkus.io/?extension-search=origin:platform%20quinoa

<img width="1288" alt="Screenshot 2023-03-17 at 16 08 39" src="https://user-images.githubusercontent.com/148698/225945302-dafcebba-b5bf-4252-8382-c1ca92a77c44.png">

There's actually a load of non-core extensions, as can be seen in https://code.quarkus.io/?extension-search=origin:other

So, it'd be nice to have a way to either show all extensions at once, or provide a toggle to enable all origins, in the project/extensions wizard (maybe replace the current show/hide descriptions buttons - that could be switched via preferences instead-.

**Comment by angelozerr** [comment]
[This PR](https://github.com/redhat-developer/vscode-quarkus/pull/815) avoid doing a filter with platform and now quinoa appears: 

![image](https://github.com/user-attachments/assets/646cd8e4-9afe-4e6a-bea3-11c1e6d2f767)

@fbricon can we close this issue or not if you want to have a platform origin filter?
