### ISSUE TITLE
CI tests install `vsce` instead of `@vscode/vsce`

### ISSUE THREAD

**Issue by datho7561** [xorye/vscode-quarkus#620]
We should switch to `@vscode/vsce`, since `vsce` is deprecated and updates aren't pushed there.

**Comment by datho7561** [comment]
https://github.com/redhat-developer/vscode-quarkus/blob/master/.github/workflows/tests.yml#L27

**Comment by angelozerr** [comment]
@datho7561 is it fixed?

**Comment by datho7561** [comment]
Yes

**Comment by datho7561** [comment]
Fixed in https://github.com/redhat-developer/vscode-quarkus/commit/b00ac25b324ad5ee16a957671ab11f1690d7979d

**Comment by angelozerr** [comment]
Thanks @datho7561
