### ISSUE TITLE
Cannot read properties of undefined (reading 'uri')

### ISSUE THREAD

**Issue by successismyonlyway** [xorye/vscode-quarkus#635]
Using vscode to create a Quarkus occurred a problem. It is showing that 'Cannot read properties of undefined (reading 'uri')'.

**Comment by angelozerr** [comment]
Could you share your project please. is it a Maven or Gradle project?

**Comment by successismyonlyway** [comment]
> Could you share your project please. is it a Maven or Gradle project?

Yes,Maven Project and My project is a initiatial project not edited.

**Comment by angelozerr** [comment]
@successismyonlyway have you again this issue?

**Comment by angelozerr** [comment]
@successismyonlyway I close the issue, please install the vscode-quarkus 1.18.0 which has been released at 26 August 2024, if you have again the problem, please reopen it.
