### ISSUE TITLE
Quarkus properties suggestion doesn't work

### ISSUE THREAD

**Issue by danieloh30** [xorye/vscode-quarkus#639]
When I type in "quarkus.", the properties ain't suggested
<img width="1265" alt="image" src="https://github.com/redhat-developer/vscode-quarkus/assets/14066977/74e2f0cc-c8bb-4275-821f-5342488b2439">

All relevant Quarkus properties were shown previously. I didn't upgrade Quarkus and Microprofile VS Code extensions though.
I even tried to uninstall and install them again but still doesn't work. Or even switched to a pre-release version but no luck.

VS Code version:
<img width="244" alt="image" src="https://github.com/redhat-developer/vscode-quarkus/assets/14066977/1a23a7a4-8e1c-4652-9ddb-5c82d3383189">

<img width="716" alt="image" src="https://github.com/redhat-developer/vscode-quarkus/assets/14066977/19b00402-b0ed-40d4-80d9-caa4bfacac09">

<img width="716" alt="image" src="https://github.com/redhat-developer/vscode-quarkus/assets/14066977/24fc410d-be8a-4a0f-8ace-0ed72e433551">

<img width="917" alt="image" src="https://github.com/redhat-developer/vscode-quarkus/assets/14066977/03b7e002-3a55-4cbb-ac3c-4bad478302b8">

**Comment by danieloh30** [comment]
After more digging, I found some interesting stuff. When I removed the quarkus-openshift extension, the suggestion works
<img width="892" alt="image" src="https://github.com/redhat-developer/vscode-quarkus/assets/14066977/54cdd832-9f58-498e-981a-f724dc6bcc19">
<img width="892" alt="image" src="https://github.com/redhat-developer/vscode-quarkus/assets/14066977/0c3c7c8a-ffc3-4c18-bc7c-0136055555c8">
But when I added the openshift extension again, 
<img width="892" alt="image" src="https://github.com/redhat-developer/vscode-quarkus/assets/14066977/11c84c78-c62e-42c0-bb87-8551750617ef">
The suggestion doesn't work again. I also saw the error in the Tools for Microprofile output.
<img width="1267" alt="image" src="https://github.com/redhat-developer/vscode-quarkus/assets/14066977/f263ba1a-d42e-410b-83f1-c2a569ad2b60">

**Comment by angelozerr** [comment]
Same issue than https://github.com/redhat-developer/vscode-quarkus/issues/638
