### ISSUE TITLE
Run tests pipeline with NodeJS 18.x

### ISSUE THREAD

**Issue by djelinek** [xorye/vscode-quarkus#683]
[ExTester](https://github.com/redhat-developer/vscode-extension-tester) is finally supporting NodeJS 18.x versions, so full tests pipeline can now used latest 18.x build of NodeJS.

This was fixed before to 18.15.x [here](https://github.com/redhat-developer/vscode-quarkus/commit/b00ac25b324ad5ee16a957671ab11f1690d7979d) which was maximal supported version that time.

FYI @datho7561

**Comment by datho7561** [comment]
Thank you for the notice!
