### ISSUE TITLE
No parameter `it` found for `panel` user tag. qute(UndefinedParameter)

### ISSUE THREAD

**Issue by geertvanleemputten** [xorye/vscode-quarkus#700]
Example:
{#panel title="COMPANY LOGO" company}

In this case company will be marked in yellow, with:
No parameter `it` found for `panel` user tag. qute(UndefinedParameter)

**Comment by angelozerr** [comment]
Could you share your project please.

**Comment by angelozerr** [comment]
@geertvanleemputten without seeing your panel usertag, it is difficult to do something.

Thanksfor sharing your project.

**Comment by angelozerr** [comment]
In your panel user tag you should use `{it}` to consume company, right?

**Comment by angelozerr** [comment]
If you use a parameter without equals like you did with company 

It means that user tag should define an it  objext part like

{it}

If you dont define it you have this error.

I close this issue since I have no answer. Please reopen it if my answer is not enough for you.
