### ISSUE TITLE
`custom-named-bean` cannot be resolved to an object. qute(UndefinedObject)

### ISSUE THREAD

**Issue by geertvanleemputten** [xorye/vscode-quarkus#701]
My named CDI beans are not being resolved by the VSCode plugin, but the ones from Quarkus are.

Example:
<img width="256" height="256" src="{inject:images.format(company.logo, 256, 256)}" />

`images` will get marked in yellow: "`images` cannot be resolved to an object. qute(UndefinedObject)"
For the `I18N` named bean from quarkus, it does not seem to be an issue.

**Comment by angelozerr** [comment]
Could you share your project please.

**Comment by angelozerr** [comment]
@geertvanleemputten I see a blank image, could you share your project please.
