### ISSUE TITLE
Camel Quarkus project not recognized right away as a Quarkus one

### ISSUE THREAD

**Issue by apupier** [xorye/vscode-quarkus#740]
steps to reproduce:
1. install [VS Code Language support for Apache Camel](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-apache-camel) (and VS Code Quarkus of course)
2. open a folder for the VS Code instance
3. Call command: Create a Camel Route with Yaml DSL (with name `demo` for instance)
4. Call command: Create a Camel Quarkus project
5. Call command:  Debug Quarkus

--> There is a notification message mentioning that there is no Quarkus project found

Workarounds:
* Call command Reload Window , then you can call command:  Debug Quarkus
* or create a dummy Java file

**Comment by fbricon** [comment]
looks like "Debug Quarkus" is not coming from our extension (it should be prefixed with "Quarkus:")
<img width="599" alt="Screenshot 2024-05-15 at 14 53 37" src="https://github.com/redhat-developer/vscode-quarkus/assets/148698/57245122-bf9a-4366-a0da-6999fe594af0">

**Comment by fbricon** [comment]
nope, that's us :-)
https://github.com/redhat-developer/vscode-quarkus/blob/238576e21ed434057106a756504b6454c4bab8b1/package.json#L143

**Comment by fbricon** [comment]
I can't reproduce the problem following the instructions. `./mvnw quarkus:dev` is executed

**Comment by apupier** [comment]
I cannot anymore neither...

@lordrip do you still reproduce? Do you see something in the steps to reproduce that is missing?

**Comment by lordrip** [comment]
@apupier those were the reproduction steps, but after reproducing it constantly 4 times during a call, now I cannot reproduce it anymore, I'll stay tuned if it happens again. Thanks for checking this out @fbricon

**Comment by apupier** [comment]
closing until we find how to reproduce again or have more information
