### ISSUE TITLE
Use category `Quarkus` for all commands

### ISSUE THREAD

**Issue by apupier** [xorye/vscode-quarkus#741]
currently, there is `Quarkus: ` as a prefix for most of the commands. In the Ui, it looks then similar to using a `category` but it is not leveraging the full power of VS Code API.

note: missing the `Quarkus:` for `Debug Quarkus` command

**Comment by fbricon** [comment]
I think the reason is the command is used to be displayed in the launch menu on the top right

<img width="141" alt="Screenshot 2024-05-15 at 15 51 25" src="https://github.com/redhat-developer/vscode-quarkus/assets/148698/5dc6f010-c2c2-48b6-82e5-d157d1630500">


The fix is actually to not display this command in the command palette

**Comment by apupier** [comment]
The category should not be displayed at this place. This is the benefit of using categories:

```
Presentation of contributed commands depends on the containing menu. The Command Palette, for instance, prefixes commands with their category, allowing for easy grouping. However, the Command Palette doesn't show icons nor disabled commands. The editor context menu, on the other hand, shows disabled items but doesn't show the category label.
```

https://code.visualstudio.com/api/references/contribution-points#contributes.commands

The availability in the command palette is useful. (this is where I searched for it)

**Comment by fbricon** [comment]
There's already a "Debug current Quarkus project" command. Having 2 roughly identical commands here is too confusing.
<img width="603" alt="Screenshot 2024-05-15 at 16 04 46" src="https://github.com/redhat-developer/vscode-quarkus/assets/148698/ade0d468-1c81-45b8-b1c3-6531cfc7f400">

**Comment by apupier** [comment]
ok so we want to hide the `Debug Quarkus` from command palette. https://github.com/redhat-developer/vscode-quarkus/issues/743
it remains interesting to use categories for all commands.
