### ISSUE TITLE
Unrecognized property mp.messaging.* when Channel annotation is used along with Multi

### ISSUE THREAD

**Issue by dmarrazzo** [xorye/vscode-quarkus#750]
Hi all,

I've noticed that quarkus extension for vscode is not able to recognize the following annotation:

```java
    @Channel("quotes")
    Multi<Quote> quotes;
```

In fact the property file raise warnings:

![Screenshot from 2024-05-21 17-24-37](https://github.com/redhat-developer/vscode-quarkus/assets/2084600/e2bcbffe-c873-4da2-90b5-e38a29168700)

```
Unrecognized property 'mp.messaging.incoming.quotes.connector', it is not referenced in any Java files
Unrecognized property 'mp.messaging.incoming.quotes.topic', it is not referenced in any Java files
```

Here my project if you need a quick reproducer:

https://github.com/Red-Hat-EMEA-SSA-AppDev-Team/amq-broker-demo

Thank you

**Comment by angelozerr** [comment]
Thanks so much @dmarrazzo to report your detailled issue.

The fix should be done in LSP4MP https://github.com/eclipse/lsp4mp/blob/b6ea114143bb32f2dd0b33037392f891952ff302/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/reactivemessaging/properties/MicroProfileReactiveMessagingProvider.java#L151

Today we support only field which uses `Emitter`:

```java
@Inject
@Channel("prices")
Emitter<double> pricesEmitter;
```

It seems we should support Multi too, do you see another class that we should support too?

**Comment by dmarrazzo** [comment]
Hello @angelozerr 

I've just checked in this document: https://quarkus.io/guides/kafka

It looks that those are the possible combinations:

```java
@Channel("prices") Multi<Double> streamOfPayloads;

@Channel("prices") Multi<Message<Double>> streamOfMessages;

@Channel("prices") Publisher<Double> publisherOfPayloads;

@Channel("prices") Publisher<Message<Double>> publisherOfMessages;

@Channel("kafka") KafkaTransactions<Fruit> kafkaTx;

@Channel("price-create") MutinyEmitter<Double> priceEmitter;

@Channel("request-reply") KafkaRequestReply<Integer, String> requestReply;
```

Thank you for the prompt reply!

**Comment by angelozerr** [comment]
Thanks @dmarrazzo for your feedback!

**Comment by dmarrazzo** [comment]
Hi @angelozerr, 

out of curiosity, do you have a guess on the resolution time frame?

**Comment by angelozerr** [comment]
> out of curiosity, do you have a guess on the resolution time frame?

We are busy to create a release with our LSP support for IntelliJ https://github.com/redhat-developer/lsp4ij that we plan to do this week, but after that I will switch again to work on Qute / Quarkus support (next week I think) and I will take care of this issue on JDT and IntelliJ both. I think this issue is not a big deal (I hope).

**Comment by angelozerr** [comment]
Once the PR for JDT will be merged, you will able to install  prerlease of vscode-quarkus (see https://github.com/redhat-developer/vscode-xml?tab=readme-ov-file#contributing to know how to do that with vscode-xml, but it is the same thing for vscode-quarkus).

If I have no problem to implement this issue, perhaps next week you will have this feature by installing prerelease of vscode-quarkus.

**Comment by fbricon** [comment]
@angelozerr I think we should simply remove the check on the return type https://github.com/eclipse/lsp4mp/blob/b6ea114143bb32f2dd0b33037392f891952ff302/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/reactivemessaging/properties/MicroProfileReactiveMessagingProvider.java#L152

and collect anything that is annotated `@Channel`

**Comment by dmarrazzo** [comment]
Thank you very much @angelozerr and @fbricon 
There's no hurry, it was just curiosity.

**Comment by angelozerr** [comment]
> and collect anything that is annotated @Channel

Indeed it is a very simply solution :) but if user set wrong type, it will have completion although it will be wrong.

**Comment by fbricon** [comment]
better have an accidental false positive than false negative errors all over the place
