### ISSUE TITLE
qute(NoMatchingTemplate) if using @CheckedTemplate with basePath

### ISSUE THREAD

**Issue by LukasLeppich** [xorye/vscode-quarkus#787]
VSCode shows the following error if a `@CheckedTemplate` with `basePath` is used:
`No template matching the path Todos/index could be found for: rest.Todos$Templatesqute(NoMatchingTemplate)`

The application starts as normal without errors.

VSCode Quarkus Extension version: v1.17.0

Reproduce:
Checkout https://github.com/ia3andy/htmx-todo
Change `@CheckedTemplate` in `Todos.java` to:
``` java
@CheckedTemplate(basePath="todo_v1")
public static class Templates {
```
Rename `Todos` directory in src/main/resources/templates to `todo_v1`

**Comment by fbricon** [comment]
Indeed https://github.com/redhat-developer/quarkus-ls/issues/893 needs to be fixed
