### ISSUE TITLE
Update release for 1.18.0 

### ISSUE THREAD

**Issue by mohitsuman** [xorye/vscode-quarkus#812]
This issue tracks the preparation and release of version 1.18.0 for the VS Code Quarkus extension.

- Add all new features, bug fixes, and improvements since the last release.
- Update the Release section.  https://github.com/redhat-developer/vscode-quarkus/releases

**Comment by angelozerr** [comment]
@mohitsuman I'm working on all release of LSP4MP,  Quarkus LS, vscode-microprofile, vscode-quarkus and IJ Quarkus and I plan (I hope) to create them this thursday

**Comment by angelozerr** [comment]
Done, see https://github.com/redhat-developer/vscode-quarkus/releases/tag/1.18.0
