### ISSUE TITLE
Cannot publish to OpenVSX due to out of date NodeJS

### ISSUE THREAD

**Issue by datho7561** [xorye/vscode-quarkus#857]
When attempting to publish to Open VSX via GitHub Actions:

```
Run ovsx publish -p ***  --packagePath vscode-quarkus/vscode-quarkus-*-${GITHUB_RUN_NUMBER}.vsix
ovsx requires at least NodeJS version 20. Check your installed version with `node --version`.
Error: Process completed with exit code 1.
```

We should upgrade the version of node used in the CD pipeline, since node 18 is no longer supported.

**Comment by rgrunber** [comment]
Looks like this is due to the recent 0.10.0,  https://www.npmjs.com/package/ovsx/v/0.10.0?activeTab=versions

**Comment by datho7561** [comment]
It doesn't seem like they have any sort of CHANGELOG for the CLI tool. The release tab on the GitHub repo doesn't even list the release. I'm guessing the API break was switching to Node 20, but that's not written down anywhere obvious
